# Generated by Django 6.1 on 2026-08-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
