# Generated by Django 6.1.1 on 2026-10-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_es_admin_general_alter_empleado_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin_general',
        ),
    ]
