# Generated by Django 6.1 on 2026-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(default='/media/fotos_trabajo/ejemplo.jpg', upload_to='model/fotos_trabajo/'),
            preserve_default=False,
        ),
    ]
