# Generated by Django 6.1 on 2026-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacion_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(upload_to='fotos_trabajo/'),
        ),
    ]
