# Generated by Django 6.1.1 on 2026-09-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_publicacion_foto'),
        ('usuarios', '0002_usuario_foto_alter_usuario_dni_empleado_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='titulo',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='urgencia',
            field=models.CharField(blank=True, choices=[('urgente', 'Urgente'), ('normal', 'Normal')], default='normal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos_trabajo/'),
        ),
        migrations.CreateModel(
            name='busquedaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('habilidades_requeridas', models.ManyToManyField(blank=True, related_name='ofertas', to='publicaciones.habilidad')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.busquedaempleado'),
        ),
        migrations.CreateModel(
            name='busquedaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='empleados', to='publicaciones.habilidad')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='busqueda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.busquedaempleo'),
        ),
    ]
