# Generated by Django 6.1.1 on 2026-10-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_habilidad_remove_publicacion_autor_and_more'),
        ('usuarios', '0003_remove_usuario_es_admin_general_alter_empleado_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='busquedaempleo',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='busquedaempleo',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='busqueda',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='requerimientos', to='publicaciones.habilidad'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_trabajo/'),
        ),
        migrations.DeleteModel(
            name='busquedaEmpleado',
        ),
        migrations.DeleteModel(
            name='busquedaEmpleo',
        ),
    ]
