# Generated by Django 6.1.1 on 2026-10-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_remove_publicacion_oferta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='id_empleado',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='id_empresa',
            new_name='empresa',
        ),
    ]
